# -*- coding: utf-8 -*-
"""ANOVA + effect_[results].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpGnJ1-HqKgfs1Ou_8HHDe69dallbuZs
"""

import pandas as pd
import numpy as np
from scipy.stats import f_oneway, levene
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df = pd.read_csv('survey_data_clean.csv')

screen_map = {
    'Less than 2 hours': 1, '2–4 hours': 2, '4–6 hours': 3,
    '6–8 hours': 4, 'More than 8 hours': 5
}
df['ScreenTimeNum'] = df['  Average daily screen time  '].map(screen_map)

usage_map = {
    'Never': 1, 'Rarely': 2, 'Sometimes': 3, 'Often': 4, 'Always': 5
}
df['UsageStudyNum'] = df['  Phone usage during studying/working hours  '].map(usage_map)

df['MorningCheckNum'] = df['  Do you check your phone within 5 minutes of waking up?  '].map({'Yes': 1, 'No': 0})
df['StressNum'] = pd.to_numeric(df['  Self-reported stress level  '], errors='coerce')

df['FocusNum'] = pd.to_numeric(df['   I can focus on tasks for long periods without distraction  '], errors='coerce')
df['LoseFocusNum'] = pd.to_numeric(df['I often lose focus due to my smartphone '], errors='coerce')
df['ProductiveNum'] = pd.to_numeric(df['I feel productive during my study/work sessions '], errors='coerce')
df['ProcrastinateNum'] = pd.to_numeric(df['I tend to procrastinate using my phone '], errors='coerce')
df['DifficultyNum'] = pd.to_numeric(df['I find it difficult to stay away from my phone during tasks '], errors='coerce')

df['AttentionComp'] = df[['FocusNum', 'LoseFocusNum', 'DifficultyNum']].mean(axis=1)

df_clean = df[['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum',
               'AttentionComp', 'ProductiveNum', 'ProcrastinateNum']].dropna()

cluster_features = ['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum']
X = df_clean[cluster_features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clean['Cluster'] = kmeans.fit_predict(X_scaled)

def cohen_effect_size(eta_sq):
    if eta_sq < 0.01:
        return "very small"
    elif eta_sq < 0.06:
        return "small"
    elif eta_sq < 0.14:
        return "medium"
    else:
        return "large"

def calculate_eta_squared_manual(groups):
    all_values = np.concatenate(groups)
    grand_mean = np.mean(all_values)
    n_total = len(all_values)

    ss_between = 0
    for group in groups:
        n = len(group)
        mean = np.mean(group)
        ss_between += n * (mean - grand_mean) ** 2

    ss_within = 0
    for group in groups:
        mean = np.mean(group)
        ss_within += np.sum((group - mean) ** 2)

    ss_total = ss_between + ss_within
    eta_sq = ss_between / ss_total if ss_total > 0 else 0
    return eta_sq, ss_between, ss_within, ss_total

print("=" * 70)
print("ANOVA WITH EFFECT SIZE (η²) MANUAL CALCULATION")
print("=" * 70)
print(f"Sample: N = {len(df_clean)}")
print()

cluster_sizes = df_clean['Cluster'].value_counts().sort_index()
print("Cluster Sizes:")
print(cluster_sizes)
print()

cluster_means = df_clean.groupby('Cluster')[['AttentionComp', 'ProductiveNum', 'ProcrastinateNum']].mean().round(3)
print("Cluster Means:")
print(cluster_means)
print()

variables = ['AttentionComp', 'ProductiveNum', 'ProcrastinateNum']
variable_labels = ['Attention', 'Productive', 'Procrastination']

for var, label in zip(variables, variable_labels):
    print("=" * 70)
    print(f"Variable: {label}")
    print("-" * 70)

    groups = [df_clean[df_clean['Cluster'] == i][var].dropna().values for i in range(3)]
    f_stat, p_val = f_oneway(*groups)

    lev_stat, lev_p = levene(*groups)
    print(f"Levene's test (homogeneity): W = {lev_stat:.3f}, p = {lev_p:.4f}")

    print(f"ANOVA: F(2, {len(df_clean)-3}) = {f_stat:.3f}, p = {p_val:.4f}")

    if p_val < 0.05:
        eta_sq, ss_between, ss_within, ss_total = calculate_eta_squared_manual(groups)
        effect_label = cohen_effect_size(eta_sq)
        print(f"SS_between = {ss_between:.3f}")
        print(f"SS_within = {ss_within:.3f}")
        print(f"SS_total = {ss_total:.3f}")
        print(f"Effect size (η²): {eta_sq:.3f} ({effect_label} effect, Cohen, 1988)")

        tukey = pairwise_tukeyhsd(endog=df_clean[var], groups=df_clean['Cluster'], alpha=0.05)
        print("\nTukey HSD Post-hoc:")
        print(tukey)
        print()

        sig_pairs = []
        for i in range(len(tukey.groupsunique)):
            for j in range(i+1, len(tukey.groupsunique)):
                idx = len(sig_pairs)
                meandiff = tukey.meandiffs[idx]
                p_adj = tukey.pvalues[idx]
                if p_adj < 0.05:
                    sig_pairs.append(f"Cluster {tukey.groupsunique[i]} vs Cluster {tukey.groupsunique[j]}: diff = {meandiff:.3f}, p = {p_adj:.4f}")

        if sig_pairs:
            print("Significant pairwise differences:")
            for pair in sig_pairs:
                print(f"  {pair}")
        else:
            print("No significant pairwise differences found.")
    else:
        print("ANOVA not significant. No post-hoc test performed.")

    print()

print("=" * 70)
print("SUMMARY TABLE")
print("=" * 70)
print("Variable       F(2,91)    p       η²      Effect")
print("-" * 70)

for var, label in zip(variables, variable_labels):
    groups = [df_clean[df_clean['Cluster'] == i][var].dropna().values for i in range(3)]
    f_stat, p_val = f_oneway(*groups)
    if p_val < 0.05:
        eta_sq, _, _, _ = calculate_eta_squared_manual(groups)
        effect_label = cohen_effect_size(eta_sq)
        print(f"{label:14} {f_stat:.3f}     {p_val:.4f}  {eta_sq:.3f}   {effect_label}")
    else:
        print(f"{label:14} {f_stat:.3f}     {p_val:.4f}  N/A     N/A")