# -*- coding: utf-8 -*-
"""figures_[results].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpGnJ1-HqKgfs1Ou_8HHDe69dallbuZs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.stats import pearsonr
import os

if not os.path.exists('figures'):
    os.makedirs('figures')

df = pd.read_csv('survey_data_clean.csv')

screen_map = {
    'Less than 2 hours': 1, '2–4 hours': 2, '4–6 hours': 3,
    '6–8 hours': 4, 'More than 8 hours': 5
}
df['ScreenTimeNum'] = df['  Average daily screen time  '].map(screen_map)

social_map = {
    'Less than 1 hour': 1, '1–3 hours': 2, '3–5 hours': 3,
    '5–7 hours': 4, 'More than 7 hours': 5
}
df['SocialMediaNum'] = df['  Social media usage per day  '].map(social_map)

sleep_map = {
    'Less than 5 hours': 1, '5–6 hours': 2, '6–7 hours': 3,
    '7–8 hours': 4, 'More than 8 hours': 5
}
df['SleepNum'] = df['  Average sleep duration  '].map(sleep_map)

usage_map = {
    'Never': 1, 'Rarely': 2, 'Sometimes': 3, 'Often': 4, 'Always': 5
}
df['UsageStudyNum'] = df['  Phone usage during studying/working hours  '].map(usage_map)

df['MorningCheckNum'] = df['  Do you check your phone within 5 minutes of waking up?  '].map({'Yes': 1, 'No': 0})
df['StressNum'] = pd.to_numeric(df['  Self-reported stress level  '], errors='coerce')

df['FocusNum'] = pd.to_numeric(df['   I can focus on tasks for long periods without distraction  '], errors='coerce')
df['LoseFocusNum'] = pd.to_numeric(df['I often lose focus due to my smartphone '], errors='coerce')
df['ProductiveNum'] = pd.to_numeric(df['I feel productive during my study/work sessions '], errors='coerce')
df['ProcrastinateNum'] = pd.to_numeric(df['I tend to procrastinate using my phone '], errors='coerce')
df['DifficultyNum'] = pd.to_numeric(df['I find it difficult to stay away from my phone during tasks '], errors='coerce')

df['AttentionComp'] = df[['FocusNum', 'LoseFocusNum', 'DifficultyNum']].mean(axis=1)
df['ProductivityComp'] = df[['ProductiveNum', 'ProcrastinateNum']].mean(axis=1)

df_clean = df[[
    'ScreenTimeNum', 'SocialMediaNum', 'UsageStudyNum',
    'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp'
]].dropna()

print(f"Sample: N = {len(df_clean)}")

# =============================================
# 1. HEATMAP
# =============================================

corr_vars = ['ScreenTimeNum', 'SocialMediaNum', 'UsageStudyNum',
             'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp']

corr_matrix = df_clean[corr_vars].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix,
            annot=True,
            cmap='Blues',
            center=0,
            vmin=-1, vmax=1,
            fmt='.2f',
            square=True,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8})

plt.title('Correlation Matrix of Key Variables', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('figures/correlation_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()
plt.close()

print("Heatmap saved as 'figures/correlation_heatmap.png'")

# =============================================
# 2. SCATTER PLOT
# =============================================

plt.figure(figsize=(8, 6))
sns.regplot(x='AttentionComp',
            y='ProductivityComp',
            data=df_clean,
            scatter_kws={'alpha': 0.6, 's': 60, 'color': '#34495E'},
            line_kws={'color': '#1A5276', 'linewidth': 2})

plt.title('Relationship Between Attention and Productivity', fontsize=14, fontweight='bold')
plt.xlabel('Attention (Composite Score)', fontsize=12)
plt.ylabel('Productivity (Composite Score)', fontsize=12)

r, p = pearsonr(df_clean['AttentionComp'], df_clean['ProductivityComp'])
plt.annotate(f'r = {r:.3f}, p = {p:.4f}',
             xy=(0.05, 0.95),
             xycoords='axes fraction',
             fontsize=12,
             bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#34495E'))

plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('figures/attention_productivity_scatter.png', dpi=300, bbox_inches='tight')
plt.show()
plt.close()

print("Scatter plot saved as 'figures/attention_productivity_scatter.png'")

# =============================================
# 3. CLUSTER PROFILES
# =============================================

cluster_features = ['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum']
X = df_clean[cluster_features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clean['Cluster'] = kmeans.fit_predict(X_scaled)

cluster_profiles = df_clean.groupby('Cluster')[
    ['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum',
     'AttentionComp', 'ProductivityComp']
].mean().round(3)

cluster_sizes = df_clean['Cluster'].value_counts().sort_index()

plot_data = cluster_profiles.T
plot_data.columns = [f'Cluster {i} (n={cluster_sizes[i]})' for i in range(3)]

fig, ax = plt.subplots(figsize=(10, 6))
plot_data.plot(kind='bar', ax=ax, color=['#1B4F72', '#2E86C1', '#85C1E9'])

plt.title('Cluster Profiles: Mean Scores Across Variables', fontsize=14, fontweight='bold')
plt.xlabel('Variable', fontsize=12)
plt.ylabel('Mean Score', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('figures/cluster_profiles.png', dpi=300, bbox_inches='tight')
plt.show()
plt.close()

print("Cluster profiles saved as 'figures/cluster_profiles.png'")

# =============================================
# 4. CLUSTER SIZES
# =============================================

plt.figure(figsize=(6, 6))
plt.pie(cluster_sizes,
        labels=[f'Cluster {i}\n(n={cluster_sizes[i]})' for i in range(3)],
        autopct='%1.1f%%',
        colors=['#1B4F72', '#2E86C1', '#85C1E9'],
        startangle=90,
        explode=(0.05, 0, 0),
        textprops={'fontsize': 12})

plt.title('Distribution of Participants Across Clusters', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('figures/cluster_sizes.png', dpi=300, bbox_inches='tight')
plt.show()
plt.close()

print("Cluster sizes saved as 'figures/cluster_sizes.png'")

print("\nAll figures updated with blue palette.")