# -*- coding: utf-8 -*-
"""hypothesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpGnJ1-HqKgfs1Ou_8HHDe69dallbuZs
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr
from sklearn.linear_model import LinearRegression
from sklearn.utils import resample
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('survey_data_clean.csv')

screen_map = {
    'Less than 2 hours': 1, '2–4 hours': 2, '4–6 hours': 3,
    '6–8 hours': 4, 'More than 8 hours': 5
}
df['ScreenTimeNum'] = df['  Average daily screen time  '].map(screen_map)

social_map = {
    'Less than 1 hour': 1, '1–3 hours': 2, '3–5 hours': 3,
    '5–7 hours': 4, 'More than 7 hours': 5
}
df['SocialMediaNum'] = df['  Social media usage per day  '].map(social_map)

usage_map = {
    'Never': 1, 'Rarely': 2, 'Sometimes': 3, 'Often': 4, 'Always': 5
}
df['UsageStudyNum'] = df['  Phone usage during studying/working hours  '].map(usage_map)

df['MorningCheckNum'] = df['  Do you check your phone within 5 minutes of waking up?  '].map({'Yes': 1, 'No': 0})
df['StressNum'] = pd.to_numeric(df['  Self-reported stress level  '], errors='coerce')

df['FocusNum'] = pd.to_numeric(df['   I can focus on tasks for long periods without distraction  '], errors='coerce')
df['LoseFocusNum'] = pd.to_numeric(df['I often lose focus due to my smartphone '], errors='coerce')
df['ProductiveNum'] = pd.to_numeric(df['I feel productive during my study/work sessions '], errors='coerce')
df['ProcrastinateNum'] = pd.to_numeric(df['I tend to procrastinate using my phone '], errors='coerce')
df['DifficultyNum'] = pd.to_numeric(df['I find it difficult to stay away from my phone during tasks '], errors='coerce')

df['AttentionComp'] = df[['FocusNum', 'LoseFocusNum', 'DifficultyNum']].mean(axis=1)

df_clean = df[['ScreenTimeNum', 'SocialMediaNum', 'UsageStudyNum',
               'MorningCheckNum', 'StressNum', 'AttentionComp',
               'ProductiveNum', 'ProcrastinateNum']].dropna()

print(f"Sample: N = {len(df_clean)}")
print("\n" + "="*70)
print("HYPOTHESIS TESTING")
print("="*70)

print("\nH1: Smartphone usage is negatively associated with attention")
print("-"*50)

h1_results = []
usage_vars = ['ScreenTimeNum', 'SocialMediaNum', 'UsageStudyNum', 'MorningCheckNum']
for var in usage_vars:
    r, p = pearsonr(df_clean[var], df_clean['AttentionComp'])
    h1_results.append({
        'Predictor': var,
        'r': r,
        'p': p,
        'Significant': p < 0.05,
        'Direction': 'Negative' if r < 0 else 'Positive'
    })
    print(f"{var} -> Attention: r = {r:.3f}, p = {p:.4f}")

print("\nH1 Conclusion:")
if all(r > -0.1 for r in [res['r'] for res in h1_results]):
    print("H1 NOT SUPPORTED: No significant negative correlations found.")
else:
    print("H1 PARTIALLY SUPPORTED")

print("\n\nH2: Attention is positively associated with productivity and negatively with procrastination")
print("-"*50)

r_prod, p_prod = pearsonr(df_clean['AttentionComp'], df_clean['ProductiveNum'])
r_proc, p_proc = pearsonr(df_clean['AttentionComp'], df_clean['ProcrastinateNum'])

print(f"Attention -> Productive: r = {r_prod:.3f}, p = {p_prod:.4f}")
print(f"Attention -> Procrastination: r = {r_proc:.3f}, p = {p_proc:.4f}")

h2_supported = (p_prod < 0.05 and r_prod > 0) and (p_proc < 0.05 and r_proc < 0)
print("\nH2 Conclusion:")
if h2_supported:
    print("H2 FULLY SUPPORTED")
elif (p_prod < 0.05 and r_prod > 0):
    print("H2 PARTIALLY SUPPORTED (only productivity part, procrastination not significant)")
else:
    print("H2 NOT SUPPORTED")

print("\n\nH3: Attention mediates the relationship between usage and productivity")
print("-"*50)

X = df_clean['ScreenTimeNum'].values.reshape(-1, 1)
M = df_clean['AttentionComp'].values
Y = df_clean['ProductiveNum'].values

model_xy = LinearRegression().fit(X, Y)
c = model_xy.coef_[0]
print(f"Step 1: X -> Y (c) = {c:.3f}")

model_xm = LinearRegression().fit(X, M)
a = model_xm.coef_[0]
print(f"Step 2: X -> M (a) = {a:.3f}")

X_M = np.column_stack([X, M])
model_xy_m = LinearRegression().fit(X_M, Y)
b = model_xy_m.coef_[1]
c_prime = model_xy_m.coef_[0]
print(f"Step 3: M -> Y (b) = {b:.3f}, X -> Y (c') = {c_prime:.3f}")

n_bootstrap = 5000
indirect_effects = []
for _ in range(n_bootstrap):
    idx = resample(range(len(X)), n_samples=len(X), replace=True)
    X_boot, M_boot, Y_boot = X[idx], M[idx], Y[idx]
    model_xm_boot = LinearRegression().fit(X_boot, M_boot)
    a_boot = model_xm_boot.coef_[0]
    X_M_boot = np.column_stack([X_boot, M_boot])
    model_ym_boot = LinearRegression().fit(X_M_boot, Y_boot)
    b_boot = model_ym_boot.coef_[1]
    indirect_effects.append(a_boot * b_boot)

indirect_effects = np.array(indirect_effects)
ci_lower = np.percentile(indirect_effects, 2.5)
ci_upper = np.percentile(indirect_effects, 97.5)
indirect_mean = np.mean(indirect_effects)

print(f"\nIndirect effect (a x b): {indirect_mean:.3f}")
print(f"95% Bootstrap CI: [{ci_lower:.3f}, {ci_upper:.3f}]")

if ci_lower < 0 and ci_upper > 0:
    print("H3 NOT SUPPORTED: CI includes zero (no significant mediation)")
else:
    print("H3 SUPPORTED: Significant indirect effect")

print("\n" + "="*70)
print("SUMMARY")
print("="*70)
print(f"H1: {'NOT SUPPORTED' if all(r > -0.1 for r in [res['r'] for res in h1_results]) else 'PARTIALLY SUPPORTED'}")
print(f"H2: {'NOT SUPPORTED' if not h2_supported else 'SUPPORTED'}")
print(f"H3: {'NOT SUPPORTED' if ci_lower < 0 and ci_upper > 0 else 'SUPPORTED'}")