# -*- coding: utf-8 -*-
"""inter-item_correlation [productivity].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpGnJ1-HqKgfs1Ou_8HHDe69dallbuZs
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr

df = pd.read_csv('survey_data_clean.csv')

df['ProductiveNum'] = pd.to_numeric(df['I feel productive during my study/work sessions '], errors='coerce')
df['ProcrastinateNum'] = pd.to_numeric(df['I tend to procrastinate using my phone '], errors='coerce')

df_clean = df[['ProductiveNum', 'ProcrastinateNum']].dropna()

print("=" * 60)
print("RELIABILITY ANALYSIS: PRODUCTIVITY SCALE")
print("=" * 60)
print(f"Sample size: N = {len(df_clean)}")
print()

print("Descriptive statistics for individual items:")
print("-" * 40)
for col in ['ProductiveNum', 'ProcrastinateNum']:
    data = df_clean[col]
    print(f"{col}:")
    print(f"  M = {data.mean():.3f}, SD = {data.std():.3f}")
    print(f"  Min = {data.min()}, Max = {data.max()}")
    print()

print("Inter-item correlation:")
print("-" * 40)

q1 = df_clean['ProductiveNum']
q2_reversed = 6 - df_clean['ProcrastinateNum']

r, p = pearsonr(q1, q2_reversed)

print(f"Inter-item correlation:")
print(f"  r = {r:.3f}, p = {p:.4f}")
print()

spearman_brown = (2 * r) / (1 + r)
print(f"Spearman-Brown coefficient:")
print(f"  SB = {spearman_brown:.3f}")
print()

print(f"Cronbach's alpha (2 items) = {spearman_brown:.3f}")
print()

print("INTERPRETATION:")
print("-" * 40)
if r >= 0.70:
    print("Excellent inter-item correlation (> 0.70)")
elif r >= 0.50:
    print("Acceptable inter-item correlation (0.50–0.70)")
elif r >= 0.30:
    print("Moderate inter-item correlation (0.30–0.50)")
else:
    print("Weak inter-item correlation (< 0.30)")

if spearman_brown >= 0.70:
    print(f"Spearman-Brown = {spearman_brown:.3f} (>= 0.70) — scale is reliable")
else:
    print(f"Spearman-Brown = {spearman_brown:.3f} (< 0.70) — moderate reliability for research purposes")

print()
print("=" * 60)

results = {
    'N': len(df_clean),
    'inter_item_r': r,
    'inter_item_p': p,
    'spearman_brown': spearman_brown,
    'cronbach_alpha': spearman_brown
}

results_df = pd.DataFrame([results])
results_df.to_csv('productivity_reliability.csv', index=False)
print("Results saved to 'productivity_reliability.csv'")