# -*- coding: utf-8 -*-
"""K‑means_statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13istqXxiKNu8LZ-PCV8BZee8NzGdEPjK
"""

import pandas as pd
import numpy as np
from collections import Counter
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('survey_data_clean.csv')
print(f"Loaded {len(df)} responses")

screen_map = {'Less than 2 hours':1,'2–4 hours':2,'4–6 hours':3,'6–8 hours':4,'More than 8 hours':5}
df['ScreenTimeNum'] = df['  Average daily screen time  '].map(screen_map)

social_map = {'Less than 1 hour':1,'1–3 hours':2,'3–5 hours':3,'5–7 hours':4,'More than 7 hours':5}
df['SocialMediaNum'] = df['  Social media usage per day  '].map(social_map)

sleep_map = {'Less than 5 hours':1,'5–6 hours':2,'6–7 hours':3,'7–8 hours':4,'More than 8 hours':5}
df['SleepNum'] = df['  Average sleep duration  '].map(sleep_map)

study_map = {'Less than 1 hour':1,'1–3 hours':2,'3–5 hours':3,'More than 5 hours':4}
df['StudyHoursNum'] = df['  Daily study/work hours  '].map(study_map)

usage_map = {'Never':1,'Rarely':2,'Sometimes':3,'Often':4,'Always':5}
df['UsageStudyNum'] = df['  Phone usage during studying/working hours  '].map(usage_map)

df['MorningCheckNum'] = df['  Do you check your phone within 5 minutes of waking up?  '].map({'Yes':1,'No':0})
df['StressNum'] = pd.to_numeric(df['  Self-reported stress level  '], errors='coerce')

likert_cols = ['   I can focus on tasks for long periods without distraction  ',
               'I often lose focus due to my smartphone ',
               'I feel productive during my study/work sessions ',
               'I tend to procrastinate using my phone ',
               'I find it difficult to stay away from my phone during tasks ']
for col in likert_cols:
    df[col+'_num'] = pd.to_numeric(df[col], errors='coerce')

df['AttentionComp'] = df[[
    '   I can focus on tasks for long periods without distraction  _num',
    'I often lose focus due to my smartphone _num',
    'I find it difficult to stay away from my phone during tasks _num'
]].mean(axis=1)

df['ProductivityComp'] = df[[
    'I feel productive during my study/work sessions _num',
    'I tend to procrastinate using my phone _num'
]].mean(axis=1)

num_cols = ['Age', 'ScreenTimeNum', 'SocialMediaNum', 'SleepNum', 'StudyHoursNum',
            'UsageStudyNum', 'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp']


print("\n=== DESCRIPTIVE STATISTICS ===\n")
for col in num_cols:
    m = df[col].mean()
    sd = df[col].std()
    print(f"{col:20} M = {m:.2f}, SD = {sd:.2f}")

print("\n=== CORRELATION MATRIX ===\n")
corr_matrix = df[num_cols].corr()
print(corr_matrix.round(3))

corr_matrix.to_csv('correlation_matrix.csv')
print("\nCorrelation matrix saved as 'correlation_matrix.csv'")

cluster_features = ['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum']
X = df[cluster_features].dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertias = []
for k in range(2, 7):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)


plt.figure(figsize=(8,5))
plt.plot(range(2,7), inertias, 'bo-')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.savefig('figures/elbow_method.png')
plt.show()

kmeans_final = KMeans(n_clusters=3, random_state=42, n_init=10)
df_cluster = df[cluster_features].dropna().copy()
df_cluster['Cluster'] = kmeans_final.fit_predict(scaler.transform(df_cluster[cluster_features]))

print("\n=== CLUSTER PROFILES ===\n")
for cluster in sorted(df_cluster['Cluster'].unique()):
    cluster_data = df_cluster[df_cluster['Cluster'] == cluster]
    print(f"Cluster {cluster}: n = {len(cluster_data)}")
    for col in cluster_features:
        print(f"  {col}: {cluster_data[col].mean():.2f}")
    print()

df_cluster.to_csv('cluster_assignments.csv')
print("Cluster assignments saved as 'cluster_assignments.csv'")


cols_to_save = ['Age','Gender ','Level of education ','Current status '] + num_cols
df_clean = df[cols_to_save].copy()
df_clean.columns = ['Age','Gender','Education','Status','ScreenTime','SocialMedia','Sleep',
                    'StudyHours','UsageDuringStudy','MorningCheck','Stress','Attention','Productivity']
df_clean.to_csv('data_for_jasp.csv', index=False)
print("\nFile 'data_for_jasp.csv' saved for JASP")

from google.colab import files
files.download('data_for_jasp.csv')
files.download('correlation_matrix.csv')
files.download('cluster_assignments.csv')