# -*- coding: utf-8 -*-
"""Tables[2, 3, 4]_Results.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpGnJ1-HqKgfs1Ou_8HHDe69dallbuZs
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('survey_data_clean.csv')

screen_map = {
    'Less than 2 hours': 1, '2–4 hours': 2, '4–6 hours': 3,
    '6–8 hours': 4, 'More than 8 hours': 5
}
df['ScreenTimeNum'] = df['  Average daily screen time  '].map(screen_map)

social_map = {
    'Less than 1 hour': 1, '1–3 hours': 2, '3–5 hours': 3,
    '5–7 hours': 4, 'More than 7 hours': 5
}
df['SocialMediaNum'] = df['  Social media usage per day  '].map(social_map)

sleep_map = {
    'Less than 5 hours': 1, '5–6 hours': 2, '6–7 hours': 3,
    '7–8 hours': 4, 'More than 8 hours': 5
}
df['SleepNum'] = df['  Average sleep duration  '].map(sleep_map)

usage_map = {
    'Never': 1, 'Rarely': 2, 'Sometimes': 3, 'Often': 4, 'Always': 5
}
df['UsageStudyNum'] = df['  Phone usage during studying/working hours  '].map(usage_map)

df['MorningCheckNum'] = df['  Do you check your phone within 5 minutes of waking up?  '].map({'Yes': 1, 'No': 0})
df['StressNum'] = pd.to_numeric(df['  Self-reported stress level  '], errors='coerce')

df['FocusNum'] = pd.to_numeric(df['   I can focus on tasks for long periods without distraction  '], errors='coerce')
df['LoseFocusNum'] = pd.to_numeric(df['I often lose focus due to my smartphone '], errors='coerce')
df['ProductiveNum'] = pd.to_numeric(df['I feel productive during my study/work sessions '], errors='coerce')
df['ProcrastinateNum'] = pd.to_numeric(df['I tend to procrastinate using my phone '], errors='coerce')
df['DifficultyNum'] = pd.to_numeric(df['I find it difficult to stay away from my phone during tasks '], errors='coerce')

df['AttentionComp'] = df[['FocusNum', 'LoseFocusNum', 'DifficultyNum']].mean(axis=1)
df['ProductivityComp'] = df[['ProductiveNum', 'ProcrastinateNum']].mean(axis=1)

df_clean = df[['ScreenTimeNum', 'SocialMediaNum', 'SleepNum', 'UsageStudyNum',
               'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp']].dropna()
print(f"Итоговая выборка: N = {len(df_clean)}")

print("\n" + "="*70)
print("TABLE 2: DESCRIPTIVE STATISTICS")
print("="*70)

desc_vars = ['ScreenTimeNum', 'SocialMediaNum', 'SleepNum', 'UsageStudyNum',
             'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp']

desc_data = []
for var in desc_vars:
    data = df_clean[var]
    desc_data.append({
        'Variable': var,
        'M': data.mean(),
        'SD': data.std(),
        'Min': data.min(),
        'Max': data.max()
    })

desc_df = pd.DataFrame(desc_data)
desc_df = desc_df.round(3)
print(desc_df.to_string(index=False))

desc_df.to_csv('table2_descriptives.csv', index=False)
print("\n 'table2_descriptives.csv'")

print("\n" + "="*70)
print("TABLE 3: CORRELATION MATRIX")
print("="*70)

corr_vars = ['ScreenTimeNum', 'SocialMediaNum', 'UsageStudyNum',
             'MorningCheckNum', 'StressNum', 'AttentionComp', 'ProductivityComp']

corr_matrix = df_clean[corr_vars].corr()

print("\nPearson's r:")
print(corr_matrix.round(3))

corr_matrix.to_csv('table3_correlation_matrix.csv')
print("\n 'table3_correlation_matrix.csv'")

print("\n" + "="*70)
print("TABLE 4: CLUSTER PROFILES")
print("="*70)

cluster_features = ['ScreenTimeNum', 'UsageStudyNum', 'MorningCheckNum', 'StressNum']
X = df_clean[cluster_features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clean['Cluster'] = kmeans.fit_predict(X_scaled)

cluster_profiles = df_clean.groupby('Cluster')[cluster_features + ['AttentionComp', 'ProductivityComp']].mean()
cluster_profiles = cluster_profiles.round(3)
print(cluster_profiles)

cluster_profiles.to_csv('table4_cluster_profiles.csv')
print("\n Table 4 сохранена как 'table4_cluster_profiles.csv'")

print("\nCluster Sizes:")
print(df_clean['Cluster'].value_counts().sort_index())

print("\n" + "="*70)
print("CORRELATIONS WITH SIGNIFICANCE")
print("="*70)

def significance_stars(p):
    if p < 0.001:
        return '***'
    elif p < 0.01:
        return '**'
    elif p < 0.05:
        return '*'
    else:
        return ''

p_matrix = pd.DataFrame(index=corr_vars, columns=corr_vars)

for i, var1 in enumerate(corr_vars):
    for j, var2 in enumerate(corr_vars):
        r, p = pearsonr(df_clean[var1], df_clean[var2])
        p_matrix.loc[var1, var2] = f"{r:.3f}{significance_stars(p)}"

print(p_matrix.to_string())

p_matrix.to_csv('table3_correlation_with_stars.csv')
print("\n  'table3_correlation_with_stars.csv'")

print("\n" + "="*70)
print("All Tables are saved!")
print("="*70)
print("\n To Download:")
print("  - table2_descriptives.csv")
print("  - table3_correlation_matrix.csv")
print("  - table3_correlation_with_stars.csv")
print("  - table4_cluster_profiles.csv")